/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface EventEmitterInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "BuildContractConfirmed(string,address)": EventFragment;
    "BuildContractCreated(string,address,address,bool)": EventFragment;
    "BuildContractDeclined(string,address)": EventFragment;
    "BuilderChanged(string,address)": EventFragment;
    "DepositSuccess(address,uint256)": EventFragment;
    "RewardBuilder(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BuildContractConfirmed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuildContractCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuildContractDeclined"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BuilderChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositSuccess"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardBuilder"): EventFragment;
}

export type BuildContractConfirmedEvent = TypedEvent<
  [string, string] & { contractId: string; performer: string }
>;

export type BuildContractCreatedEvent = TypedEvent<
  [string, string, string, boolean] & {
    contractId: string;
    owner: string;
    busyBuilder: string;
    setBusy: boolean;
  }
>;

export type BuildContractDeclinedEvent = TypedEvent<
  [string, string] & { contractId: string; performer: string }
>;

export type BuilderChangedEvent = TypedEvent<
  [string, string] & { contractId: string; newBuilder: string }
>;

export type DepositSuccessEvent = TypedEvent<
  [string, BigNumber] & { from: string; value: BigNumber }
>;

export type RewardBuilderEvent = TypedEvent<
  [string, BigNumber] & { performer: string; reward: BigNumber }
>;

export class EventEmitter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: EventEmitterInterface;

  functions: {};

  callStatic: {};

  filters: {
    "BuildContractConfirmed(string,address)"(
      contractId?: null,
      performer?: null
    ): TypedEventFilter<
      [string, string],
      { contractId: string; performer: string }
    >;

    BuildContractConfirmed(
      contractId?: null,
      performer?: null
    ): TypedEventFilter<
      [string, string],
      { contractId: string; performer: string }
    >;

    "BuildContractCreated(string,address,address,bool)"(
      contractId?: null,
      owner?: null,
      busyBuilder?: null,
      setBusy?: null
    ): TypedEventFilter<
      [string, string, string, boolean],
      {
        contractId: string;
        owner: string;
        busyBuilder: string;
        setBusy: boolean;
      }
    >;

    BuildContractCreated(
      contractId?: null,
      owner?: null,
      busyBuilder?: null,
      setBusy?: null
    ): TypedEventFilter<
      [string, string, string, boolean],
      {
        contractId: string;
        owner: string;
        busyBuilder: string;
        setBusy: boolean;
      }
    >;

    "BuildContractDeclined(string,address)"(
      contractId?: null,
      performer?: null
    ): TypedEventFilter<
      [string, string],
      { contractId: string; performer: string }
    >;

    BuildContractDeclined(
      contractId?: null,
      performer?: null
    ): TypedEventFilter<
      [string, string],
      { contractId: string; performer: string }
    >;

    "BuilderChanged(string,address)"(
      contractId?: null,
      newBuilder?: null
    ): TypedEventFilter<
      [string, string],
      { contractId: string; newBuilder: string }
    >;

    BuilderChanged(
      contractId?: null,
      newBuilder?: null
    ): TypedEventFilter<
      [string, string],
      { contractId: string; newBuilder: string }
    >;

    "DepositSuccess(address,uint256)"(
      from?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; value: BigNumber }
    >;

    DepositSuccess(
      from?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; value: BigNumber }
    >;

    "RewardBuilder(address,uint256)"(
      performer?: null,
      reward?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { performer: string; reward: BigNumber }
    >;

    RewardBuilder(
      performer?: null,
      reward?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { performer: string; reward: BigNumber }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
