/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LaLaVilleEconomyToken } from "./LaLaVilleEconomyToken";

export { LaLaVilleEconomyToken__factory } from "./factories/LaLaVilleEconomyToken__factory";
